architecture: linux/arm

pipeline:
  publish:
    image: plugins/docker
    repo: arnulfosolis/py-led-blinker
    auto_tag: true
    auto_tag_suffix: linux-arm
    secrets:
      - docker_username
      - docker_password

