version: '2'
services:
  blinker:
    image: arnulfosolis/led-blinker:latest
    command: develop
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./src/:/app/src/
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
    devices:
      - /dev/gpiomem
